### ISSUE TITLE
Feature request: improving architect menu

### ISSUE THREAD

**Issue by Razunter** [Dubwise56/Dubs-Mint-Menus#10]
I love the architect menu in this mod, but there are things to improve:

1. Add option to sort by name by default. Currently, you have to click “sort” every game launch/load.
2. Options for size, like other menus.
3. Support for icons, preferably with [“Architect icons”](https://steamcommunity.com/sharedfiles/filedetails/?id=1195427067) mod support.
4. Maybe an option to “pin” some categories like orders and zones, so they always stay on top regardless of sorting.

**Comment by Dubwise56** [comment]
yer i'll look into that stuff

**Comment by Alviansyah** [comment]
may I add something to this? perhaps add a toggle for locking the menu's UI position as well. or restrict the UI dragging function to top part(or anywhere else instead of the entire UI) of the menu only. often times I dragged the menu UI instead of clicking the item I wanted to and it gets annoying.

**Comment by Dubwise56** [comment]
update on git master
window drag is now customized to a bar at the top of the window
added architect tab pinning, saved
a-z button now saves

cant do button scaling for the build menu because gizmo's aren't resizable, at least not safely because of mods
