### ISSUE TITLE
Bills no longer shown on tailoring bench and crafting spot after a while

### ISSUE THREAD

**Issue by PelokB575** [Dubwise56/Dubs-Mint-Menus#9]
I am having an issue that whenever I open the bills on a tailoring bench or a crafting spot, I am greeted by this: 
![image](https://user-images.githubusercontent.com/17013892/127740836-21f0817d-d00f-41e9-b915-2693043b02b8.png)

The issue wasn't present yet at the start of the game, it started appearing after a certain point. (might have been after a colonist joined, but I am not sure)

https://gist.github.com/HugsLibRecordKeeper/dd15aedca213a18e27ff454771241f76 here are the logs from HugsLib, with the error message at the end probably being related. I tried removing my other mods (except for HugsLib, Harmony and BetterLoading) but the issue persisted.

**Comment by Pastell** [comment]
[Nearly identical error](https://gist.github.com/HugsLibRecordKeeper/4ab044b2c247c208857f0b5b9e45f72f) was reported on the RimWorld Discord by SoulYard#3016.
![image](https://user-images.githubusercontent.com/6536055/127755072-7fd20616-103e-47c6-b226-d19f87dea279.png)

The issue was reportedly solved by removing [Combine Face and Hat Items](https://steamcommunity.com/sharedfiles/filedetails/?id=2559760431).
![image](https://user-images.githubusercontent.com/6536055/127755082-4f283433-203f-4c9e-96cb-5cbdbfdc9a09.png)

Of note is that @PelokB575 does not have that mod installed, and I have both _Dub Mint Menus_ and _Combine Face and Hat Items_ installed and I have no such issue. (Mint Menus is after Combine Face and Hat Items in my load order, and SoulYard's load order.)

**Comment by Dubwise56** [comment]
does the bills menu work if you close the mint bills list on the side, because my code wont run if you do that, it sounds like they have a bad config in their defs since im just checking for standard things like if the bills available and its failing on that

**Comment by PelokB575** [comment]
When I closed mint bills, the bills I made previously did show up, but then the 'Add bill' button wasn't working either (though that is not caused by Mint menus since it was still an issue when I took it out of the list)

**Comment by Dubwise56** [comment]
Oh well then it's not a problem with my mod, it's the other one breaking
the standard bills system

**Comment by PelokB575** [comment]
Okay then. I have since then started another playthrough and I didn't experience the issue there so it's possible it has been fixed there (both the add bill button and mint menus work correctly as far as I can tell). I'll close this issue now, thanks for the replies! :D
